# Generated by Django 4.2.2 on 2023-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_complaints_anonyomous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='acceptable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
